services:
  _defaults:
    autowire: true

  Aws\Credentials\Credentials:
    arguments:
      - "@=parameter('aws.s3.client.configs')['credentials']['key']"
      - "@=parameter('aws.s3.client.configs')['credentials']['secret']"
      - "@=parameter('aws.s3.client.configs')['credentials']['token']"
      - "@=parameter('aws.s3.client.configs')['credentials']['expires']"

  Aws\S3\S3Client:
    arguments:
        - {
          credentials: "@Aws\\Credentials\\Credentials",
          region: "@=parameter('aws.s3.client.configs')['region']",
          version: "@=parameter('aws.s3.client.configs')['version']"
        }

  League\Flysystem\AwsS3V3\AwsS3V3Adapter:
    arguments:
      - "@Aws\\S3\\S3Client"
      - "@=parameter('aws.s3.image.bucket')"

  League\Flysystem\Filesystem:
    arguments:
      - "@League\\Flysystem\\AwsS3V3\\AwsS3V3Adapter"
      - { visibility: "public" }

  OxidEsales\EshopCommunity\Internal\Framework\FileSystem\ImageHandlerInterface:
    class: OxidEsales\AwsS3Component\Service\MasterImageHandler
    arguments:
      - "@oxid_esales.symfony.file_system"
      - "@League\\Flysystem\\Filesystem"
    public: true