services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\AwsS3Component\Service\S3ClientServiceInterface:
    class: OxidEsales\AwsS3Component\Service\S3ClientService
    arguments:
      - '%aws.s3.client.configs%'

  OxidEsales\AwsS3Component\Service\ImageBucketFilesystemServiceInterface:
    class: OxidEsales\AwsS3Component\Service\ImageBucketFilesystemService
    arguments:
      - '@OxidEsales\AwsS3Component\Service\S3ClientServiceInterface'
      - '%aws.s3.image.bucket%'

  OxidEsales\EshopCommunity\Internal\Framework\FileSystem\ImageHandlerInterface:
    class: OxidEsales\AwsS3Component\Service\MasterImageHandler
    arguments:
      - '@oxid_esales.symfony.file_system'
      - '@OxidEsales\AwsS3Component\Service\ImageBucketFilesystemServiceInterface'
    public: true